name: ASP.NET API Pipeline

on: [push, pull_request]

jobs:
  syntax_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x 

      - name: Dependencies
        run: dotnet restore

      - name: Install FxCopAnalyzers
        run: dotnet add ApiMiniGigs/ApiMiniGigs.csproj package Microsoft.CodeAnalysis.FxCopAnalyzers 

      - name: Build and analyze
        run: dotnet build --no-restore --configuration Release /p:DebugType=None /p:DebugSymbols=false
